import type { Metadata } from "next";

import { Lato } from "next/font/google";

import { ScrollProgress } from "@/components/ui/scroll-progress";

import "./globals.css";
import { SiteHeader } from "@/components/ui/header";
import { ThemeProvider } from "@/components/ui/theme-provider";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" suppressHydrationWarning>
      <body className={`${lato.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SiteHeader />
          {children}
          <ScrollProgress />
        </ThemeProvider>
      </body>
    </html>
  );
}
